openapi: 3.0.0
info:
  title: GDI Authentication API
  description: Common broker for GDI authentication against Visma Federation Services (BankId, Freya).
  version: 1.0.6
tags:
  - name: Web authentication
    description: Authentication operations
paths:
  /api/v1/{namespace}/healthcheck:
    get:
      operationId: healthCheck
      summary: "Healthcheck of service"
      tags:
        - Status of Operations
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Service is healthy"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type:
                      string
  /api/v1/auth/login:
    get:
      operationId: login
      summary: Navigate (redirect) to login page
      description: Responds with a redirect to actual login page. Clients are encouraged to use this endpoint in standard HTML <a href=".../login">
      tags:
        - Web authentication
      parameters:
        - name: redirect_url
          in: query
          required: true
          schema:
            type: string
        - name: relay_state
          in: query
          required: false
          schema:
            type: string
      responses:
        '302':
          description: Standard HTTP redirect result with target location set in headers
  /api/v1/auth/logout:
    get:
      operationId: logout
      description: Logout token
      summary: Logout token and federated services
      tags:
        - Web authentication
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful logout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
  /api/v1/auth/profiles:
    get:
      operationId: profiles
      summary: Get signing profiles
      tags:
        - Web authentication
      responses:
        '200':
          description: List of supported profiles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
  /api/v1/auth/token:
    get:
      operationId: token
      summary: Create signed token from authentication
      tags:
        - Web authentication
      parameters:
        - name: ts_session_id
          in: query
          required: true
          schema:
            type: string
        - name: profile
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: An issued JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignResponse'
  /api/v1/auth/test-landing-page:
    get:
      operationId: testLandingPage
      summary: Fake return page
      description: "Fake return page for testing purposes. Usage: /auth/login?redirect_url=.../api/v1/auth/test-landing-page"
      tags:
        - Testing
      parameters:
        - name: ts_session_id
          in: query
          required: true
          schema:
            type: string
        - name: relayState
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Dump of session
components:
  schemas:
    Profile:
      type: object
      required:
        - id
        - description
      properties:
        id:
          type: string
        description:
          type: string
    LogoutResponse:
      type: object
    SignResponse:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    JwtClaims:
      type: object
      properties:
        expiresIn:
          type: integer
        notBefore:
          type: integer
        iss:
          type: string
        sub:
          type: string
        aud:
          type: string
        exp:
          type: integer


