name: Build and push docker image to github registry.

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set openapi version
        uses: rmeneely/update-yaml@v1
        with:
          infile: gdi-auth.openapi.yml
          varlist: info.version=${{ github.event.release.tag_name }}
      
      - name: Set package.json version
        run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      
      - name: Update repository
        run: |
          git config user.name version-updater
          git config user.email version-updater@helsingborg.se
          git add .
          git commit -m "🔖 Set versions to latest release tag"
          git push origin main

      - name: Repository Variable to Lowercase
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ghcr.io/${{ steps.string.outputs.lowercase }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger config repo update
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: helsingborg-stad
          repo: ${{ secrets.GDI_GITOPS_CONFIG_REPO }}
          github_token: ${{ secrets.GDI_GITOPS_TOKEN }}
          workflow_file_name: update-config.yml
          inputs: '{"semver": "${{ github.event.release.tag_name }}", "app": "${{ secrets.GDI_GITOPS_APP }}"}'
          wait_workflow: false
          ref: main